<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>TechnoHub.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TechnoHub.Domain\TechnoHub.Domain.csproj" />
  </ItemGroup>

</Project>
